hide_head_poem/urls.py
# coding: utf-8
from django.urls import path
from .views import HideHeadView, HideHeadIndexView


app_name = 'hide_head'

urlpatterns = [
    path('', HideHeadIndexView.as_view(), name="head_index"),
    path('<str:head>/', HideHeadView.as_view(), name='head')
]

poem_django/urls.py
from django.urls import path, include
from poet_recommendation.views import PoetIndexView

urlpatterns = [
    path('', PoetIndexView.as_view(), name="index"),
    path('poem/', include('poem_recommendation.urls')),
    path('poet/', include('poet_recommendation.urls')),
    path('search/', include('search.urls')),
    path('hide-head/', include('hide_head_poem.urls'))
]

poem_recommendation/urls.py
# coding: utf-8
from .views import PoemIndexView, PoemView
from django.urls import path


app_name = 'poem'

urlpatterns = [
    path('', PoemIndexView.as_view(), name='poem_index'),
    path('<int:pk>/', PoemView.as_view(), name='poem')
]

poet_recommendation/urls.py
# coding: utf-8
from .views import PoetIndexView, PoetView
from django.urls import path

app_name = 'poet'

urlpatterns = [
    path('', PoetIndexView.as_view(), name='poet_index'),
    path('<int:pk>', PoetView.as_view(), name='poet')
]

search/urls.py
# coding: utf-8
from django.urls import path
from .views import SearchView

app_name = 'search'

urlpatterns = [
    path('<str:text>/', SearchView.as_view(), name='search')
]

hide_head_poem/models.py
from django.db import models

poem_recommendation/models.py
from django.db import models


# class Poetry(models.Model):
#
#     class Meta:
#         db_table = 'poetry'
#
#     id = models.AutoField(primary_key=True)
#     author = models.ForeignKey('poet_recommendation.PoetryAuthor', to_field='id', on_delete=models.CASCADE, related_name='poetry', db_column='author_id')
#     title = models.CharField(max_length=255)
#     content = models.TextField()
#     yunlv_rule = models.TextField()


class Poem(models.Model):
    class Meta:
        db_table = 'poem'

    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(
        'poet_recommendation.Poet', to_field='id', on_delete=models.CASCADE, related_name='poems', db_column='author_id'
    )
    title = models.CharField(max_length=255)
    content = models.TextField()
    yunlv_rule = models.TextField()
    poem_type = models.CharField(max_length=20)

    def content_as_line(self):
        return self.content.split('|')


# class Poem2(models.Model):
#     class Meta:
#         db_table = 'poems'
#
#     id = models.AutoField(primary_key=True)
#     author = models.ForeignKey('poet_recommendation.PoemAuthor', to_field='id', on_delete=models.CASCADE, related_name='poems', db_column='author_id')
#     title = models.CharField(max_length=255)
#     content = models.TextField()
#
#     def content_as_line(self):
#         return self.content.split('|')

poet_recommendation/models.py
from django.db import models


class Poet(models.Model):
    class Meta:
        db_table = 'poet'

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    intro = models.TextField(null=True)
    dynasty = models.CharField(max_length=10, null=True)


# class PoemAuthor(models.Model):
#     class Meta:
#         db_table = 'poems_author'
#
#     id = models.AutoField(primary_key=True)
#     name = models.CharField(max_length=20)
#     intro_l = models.TextField()
#     intro_s = models.TextField()
#
#
# class PoetryAuthor(models.Model):
#     class Meta:
#         db_table = 'poetry_author'
#     id = models.AutoField(primary_key=True)
#     name = models.CharField(max_length=20)
#     intro = models.TextField()
#     dynasty = models.CharField(max_length=10)

hide_head_poem/views.py
from django.shortcuts import render
from django.views import generic
from utils.TangshiGene2 import Line5_Head


class HideHeadIndexView(generic.View):
    def get(self, request):
        return render(
            request,
            'head/head.html'
        )


class HideHeadView(generic.View):
    def get(self, request, **kwargs):

        head = kwargs.get("head")
        try:
            res = Line5_Head(head)
            res = res.split("\n")
        except Exception as e:
            res = [
                "抱歉!",
                "{}无法生成藏头诗".format(head),
            ]
        return render(
            request,
            'head/head.html',
            {
                "lines": res
            }
        )

poem_recommendation/views.py
from django.shortcuts import render
from django.views import generic
from .models import Poem
import random

# Create your views here.


class PoemIndexView(generic.ListView):
    template_name = 'poem_recommendation/poem.html'
    context_object_name = 'poem_list'
    poems = [
        {
            "title": "江南",
            "content": "江南可采莲，莲叶何田田，鱼戏莲叶间。鱼戏莲叶东，鱼戏莲叶西，鱼戏莲叶南，鱼戏莲叶北。",
            "href": "../../../static/江南.html"
        },
        {
            "title": "咏鹅",
            "content": "鹅鹅鹅，曲项向天歌。白毛浮绿水，红掌拨清波。",
            "href": "../../../static/咏鹅.html"
        },
        {
            "title": "枫桥夜泊",
            "content": "月落乌啼霜满天，江枫渔火对愁眠。姑苏城外寒山寺，夜半钟声到客船",
            "href": "../../../static/枫桥夜泊.html"
        },
        {
            "title": "静夜思",
            "content": "床前明月光，疑是地上霜。举头望明月，低头思故乡。",
            "href": "../../../static/静夜思.html"
        }
    ]

    def get_queryset(self):
        count = Poem.objects.all().count()
        rand = random.sample(range(count), 10)
        return Poem.objects.filter(id__in=rand)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['r_poem'] = random.choice(self.poems)
        return context


class PoemView(generic.DetailView):
    template_name = 'poem_recommendation/poem.html'
    context_object_name = 'poem'
    model = Poem

poet_recommendation/views.py
from django.shortcuts import render
from django.views import generic
from .models import Poet
import random


class PoetIndexView(generic.ListView):
    template_name = 'poet_recommendation/poet.html'
    context_object_name = 'poet_list'

    def get_queryset(self):
        count = Poet.objects.all().count()
        rand = random.sample(range(count), 10)
        return Poet.objects.filter(id__in=rand)


class PoetView(generic.DetailView):
    template_name = 'poet_recommendation/poet.html'
    model = Poet
    context_object_name = 'poet'

search/views.py
from django.shortcuts import render
from django.views import generic
from poet_recommendation.models import Poet
from poem_recommendation.models import Poem


class SearchView(generic.View):
    def get(self, request, **kwargs):
        text = kwargs.get('text')
        if not text:
            return
        poem_list = Poem.objects.filter(content__contains=text)
        poet_list = Poet.objects.filter(name__contains=text)
        context = {
            "poem_list": poem_list,
            "poet_list": poet_list
        }
        return render(
            request,
            'search/search.html',
            context
        )

hide_head_poem/templates/head/head.html
{% extends 'index.html' %}
{% block content %}
    <div class="search" style="">
        <input id='hide_head' type="text" placeholder="Search for..." style="width: 140px;padding: 3px;">
        <button class="btn btn-default" style="background:cornflowerblue;height: 32px;line-height: 10px;margin-bottom:5px" type="button" onclick="hide_head()">Go!</button>
    </div>
{% if lines %}
    {% for line in lines %}
    <p>{{ line }}</p>
    {% endfor %}
{% endif %}
{% endblock %}

poem_recommendation/templates/poem_recommendation/poem.html
{% extends 'index.html' %}
{% block content %}
{% if poem_list %}
    <ul class="list-group">
{#        <li class="list-group-item list-group-item-info" style="text-align: center">#}
{#            <p><a href="../../../static/jiangnan.html">江南</a></p>#}
{#            <p style="display: inline-block;text-align: center">汉乐府</p>#}
{#            <p>江南可采莲，莲叶何田田，鱼戏莲叶间。</p>#}
{#            <p>鱼戏莲叶东，鱼戏莲叶西，鱼戏莲叶南，鱼戏莲叶北</p>#}
{#        </li>#}
        <li class="list-group-item list-group-item-info" style="text-align: center">
            <p><a href="{{ r_poem.href }}">{{ r_poem.title }}</a></p>
            <p>{{ r_poem.content }}</p>
        </li>
        {% for poem in poem_list %}
            <li class="list-group-item list-group-item-info" style="text-align: center">
                <p style="display: inline-block;text-align: center"><a href="{% url 'poem:poem' poem.id %}">{{ poem.title }}</a></p>
                <br>
                <p style="display: inline-block;text-align: center">{{ poem.author.name }}</p>
                {% for line in poem.content_as_line %}
                    <p>{{ line }}</p>
                {% endfor %}
            </li>
        {% endfor %}
    </ul>
{% elif poem %}
    <div style="text-align: center">
        <p>{{ poem.title }}</p>
        <p>{{ poem.author.name }}</p>
        {% for line in poem.content_as_line %}
            <p>{{ line }}</p>
        {% endfor %}
    </div>
{% else %}
    <p>暂无推荐</p>
{% endif %}
{% endblock %}

poet_recommendation/templates/poet_recommendation/poet.html
{% extends 'index.html' %}
{% block content %}
{% if poet_list %}
    <ul class="list-group list-group-item-info">
        {% for poet in poet_list %}
            <li class="list-group-item list-group-item-info"><a href="{% url 'poet:poet' poet.id %}" style="width:100%;display: inline-block;text-align: center">{{ poet.name }}</a> </li>
        {% endfor %}
    </ul>
{% elif poet %}
    <div>
        <p>{{ poet.name }}</p>
        <p>个人简介：{{ poet.intro }}</p>
        <p>ta的作品：</p>
        {% for poem in poet.poems.all %}
            <li class="list-group-item list-group-item-info"  style="text-align: left;padding-left: 48%"><a href="{% url 'poem:poem' poem.id %}">{{ poem.title }}</a></li>
        {% endfor %}
    </div>
{% else %}
    <p>暂无推荐</p>
{% endif %}
{% endblock %}

search/templates/search/search.html
{% extends 'index.html' %}
{% block content %}
    <p style="text-align: left">查找结果:</p>
    {% if poet_list or poem_list %}
        {% if poet_list %}
            <p style="text-align: left">找到的诗人：</p>
            <ul class="list-group-item-info">
            {% for poet in poet_list %}
                <li class="list-group-item-info" style="text-align: center;margin-bottom: 10px">
                    <a href="{% url 'poet:poet' poet.id %}" style="width:100%;display: inline-block;text-align: center">{{ poet.name }}</a>
                </li>
            {% endfor %}
        </ul>
        {% endif %}
        {% if poem_list %}
            <p style="text-align: left">找到的诗：</p>
            <ul class="list-group-item-info">
                {% for poem in poem_list %}
                    <li class="list-group-item-info" style="text-align: center;margin-bottom: 10px">
                        <a href="{% url 'poem:poem' poem.id %}" style="width:100%;display: inline-block;text-align: center">{{ poem.title }}</a>
                    </li>
                {% endfor %}
        {% endif %}
    </ul>
{% else %}
    <p>未搜索到相关内容</p>
{% endif %}
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>诗词推荐{{ static }}</title>
      <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  </head>
  <body>
    <div id="panel">
      <div class="header">
        诗词天地
        <div class="toggle-button">
            <svg
            t="1558608744759"
            class="icon"
            style=""
            viewBox="0 0 1024 1024"
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            p-id="807"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            width="22"
            height="22"
          >
            <defs><style type="text/css"></style></defs>
            <path
              d="M992 160H32a32 32 0 0 1 0-64h960a32 32 0 0 1 0 64zM992 544H32a32 32 0 0 1 0-64h960a32 32 0 0 1 0 64zM992 928H32a32 32 0 0 1 0-64h960a32 32 0 0 1 0 64z"
              p-id="808"
            ></path>
          </svg>
        </div>
      </div>
      <div class="nav">
        <a href="{% url 'poet:poet_index' %}">大艺术家</a>
        <a href="{% url 'poem:poem_index' %}">每日推荐</a>
        <a href="{% url 'hide_head:head_index' %}">为你写诗</a>
      </div>
      <div class="content list-group-item-info" style="height: 100%;width:100%;display: inline-block;text-align: center;position: absolute;top: 90px;bottom: 0;">
          {% block content %}{% endblock %}
      </div>
    </div>
    <div id="menu" class="list-group-item-success">
        <div class="search" style="">
            <input id='search' type="text" placeholder="Search for..." style="width: 140px;padding: 3px;">
            <button class="btn btn-default" style="background:cornflowerblue;height: 32px;line-height: 10px;margin-bottom:5px" type="button" onclick="search()">Go!</button>
        </div>
        <div class="part1"><a href="{% url 'poet:poet_index' %}">大艺术家</a></div>
        <div class="part2"><a href="{% url 'poem:poem_index' %}">每日推荐</a></div>
        <div class="part3"><a href="{% url 'hide_head:head_index' %}"></a>为你写诗</div>
    </div>
    <script src="{% static 'js/slide.js' %}"></script>
    <script>
      var slideout = new Slideout({
        panel: document.getElementById("panel"),
        menu: document.getElementById("menu"),
        padding: 256,
        tolerance: 70
      });

      document
        .querySelector(".toggle-button")
        .addEventListener("click", function() {
          slideout.toggle();
        });
      function search() {
          text = document.getElementById('search').value;
          if(text){
              window.location.href = "/search/" + text + "/"
          }
      }
      function hide_head(){
          text = document.getElementById('hide_head').value;
          console.log(text);
          if(text){
              window.location.href = "/hide-head/" + text + "/"
          }
      }
    </script>
  </body>
</html>